# Week3 Logistic Regression - Categories

## Highlights
- sklearn train_test_split: split your dataset
- sklearn.metrics mutual_info_score: it tells us how much we can learn about one variable if we know the value of another
- one-hot encoding to deal with categorical data
- calculate the accuracy of your prediction

In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [49]:
# download data
# data = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"
# !wget $data

In [50]:
# read data
df = pd.read_csv("data.csv")
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [51]:
df.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [52]:
# only choose certain columns

selected_df  = df[
    ["Make",
    "Model",
    "Year",
    "Engine HP",
    "Engine Cylinders",
    "Transmission Type",
    "Vehicle Style",
    "highway MPG",
    "city mpg",
    "MSRP"]
].copy()
selected_df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,highway MPG,city mpg,MSRP
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,34500
...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,4dr Hatchback,23,16,46120
11910,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,4dr Hatchback,23,16,56670
11911,Acura,ZDX,2012,300.0,6.0,AUTOMATIC,4dr Hatchback,23,16,50620
11912,Acura,ZDX,2013,300.0,6.0,AUTOMATIC,4dr Hatchback,23,16,50920
11913,Lincoln,Zephyr,2006,221.0,6.0,AUTOMATIC,Sedan,26,17,28995

In [53]:
# format the data
selected_df.columns = selected_df.columns.str.replace(" ", "_").str.lower()
selected_df_columns = list(selected_df.dtypes.index)
selected_df_columns

['make',
 'model',
 'year',
 'engine_hp',
 'engine_cylinders',
 'transmission_type',
 'vehicle_style',
 'highway_mpg',
 'city_mpg',
 'msrp']

In [54]:
for c in selected_df_columns:
    if selected_df[c].dtype == "object":
        selected_df[c] = selected_df[c].str.lower().str.replace(" ", "_")
    
selected_df.head()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,msrp
0,bmw,1_series_m,2011,335.0,6.0,manual,coupe,26,19,46135
1,bmw,1_series,2011,300.0,6.0,manual,convertible,28,19,40650
2,bmw,1_series,2011,300.0,6.0,manual,coupe,28,20,36350
3,bmw,1_series,2011,230.0,6.0,manual,coupe,28,18,29450
4,bmw,1_series,2011,230.0,6.0,manual,convertible,28,18,34500

In [55]:
# rename msrp to price
selected_df = selected_df.rename(columns={"msrp": "price"})
selected_df

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,price
0,bmw,1_series_m,2011,335.0,6.0,manual,coupe,26,19,46135
1,bmw,1_series,2011,300.0,6.0,manual,convertible,28,19,40650
2,bmw,1_series,2011,300.0,6.0,manual,coupe,28,20,36350
3,bmw,1_series,2011,230.0,6.0,manual,coupe,28,18,29450
4,bmw,1_series,2011,230.0,6.0,manual,convertible,28,18,34500
...,...,...,...,...,...,...,...,...,...,...
11909,acura,zdx,2012,300.0,6.0,automatic,4dr_hatchback,23,16,46120
11910,acura,zdx,2012,300.0,6.0,automatic,4dr_hatchback,23,16,56670
11911,acura,zdx,2012,300.0,6.0,automatic,4dr_hatchback,23,16,50620
11912,acura,zdx,2013,300.0,6.0,automatic,4dr_hatchback,23,16,50920
11913,lincoln,zephyr,2006,221.0,6.0,automatic,sedan,26,17,28995

In [56]:
selected_df.isnull().sum()

make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
price                 0
dtype: int64

In [57]:
# Fill in the missing values of the selected features with 0
selected_df.fillna(0, inplace=True)

In [58]:
selected_df.isnull().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
price                0
dtype: int64

In [59]:
#Q1 What is the most frequent observation (mode) for the column transmission_type?
selected_df["transmission_type"].mode()

0    automatic
Name: transmission_type, dtype: object

In [60]:
# turn the price variable from numeric into a binary format
selected_df["above_average"] = (selected_df.price > selected_df["price"].mean()).astype(int)
selected_df

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,price,above_average
0,bmw,1_series_m,2011,335.0,6.0,manual,coupe,26,19,46135,1
1,bmw,1_series,2011,300.0,6.0,manual,convertible,28,19,40650,1
2,bmw,1_series,2011,300.0,6.0,manual,coupe,28,20,36350,0
3,bmw,1_series,2011,230.0,6.0,manual,coupe,28,18,29450,0
4,bmw,1_series,2011,230.0,6.0,manual,convertible,28,18,34500,0
...,...,...,...,...,...,...,...,...,...,...,...
11909,acura,zdx,2012,300.0,6.0,automatic,4dr_hatchback,23,16,46120,1
11910,acura,zdx,2012,300.0,6.0,automatic,4dr_hatchback,23,16,56670,1
11911,acura,zdx,2012,300.0,6.0,automatic,4dr_hatchback,23,16,50620,1
11912,acura,zdx,2013,300.0,6.0,automatic,4dr_hatchback,23,16,50920,1
11913,lincoln,zephyr,2006,221.0,6.0,automatic,sedan,26,17,28995,0

In [61]:
# set up the validation framework
from sklearn.model_selection import train_test_split

selected_df_full_train, selected_df_test = train_test_split(selected_df, test_size=0.2, random_state=42)
selected_df_train, selected_df_val = train_test_split(selected_df_full_train, test_size=0.25, random_state=42)

In [62]:
len(selected_df_train), len(selected_df_val), len(selected_df_test)

(7148, 2383, 2383)

In [63]:
selected_df_train = selected_df_train.reset_index(drop=True)
selected_df_val = selected_df_val.reset_index(drop=True)
selected_df_test = selected_df_test.reset_index(drop=True)

In [64]:
y_train = selected_df_train["above_average"].values
y_val = selected_df_val["above_average"].values
y_test = selected_df_test["above_average"].values

del selected_df_train["price"]
del selected_df_val["price"]
del selected_df_test["price"]
del selected_df_train["above_average"]
del selected_df_val["above_average"]
del selected_df_test["above_average"]

In [65]:
selected_df_train

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg
0,mitsubishi,endeavor,2011,225.0,6.0,automatic,4dr_suv,19,15
1,kia,borrego,2009,276.0,6.0,automatic,4dr_suv,21,17
2,lamborghini,gallardo,2012,570.0,10.0,manual,convertible,20,12
3,chevrolet,colorado,2016,200.0,4.0,automatic,crew_cab_pickup,27,20
4,pontiac,vibe,2009,158.0,4.0,automatic,4dr_hatchback,26,20
...,...,...,...,...,...,...,...,...,...
7143,toyota,sienna,2016,266.0,6.0,automatic,passenger_minivan,25,18
7144,chevrolet,hhr,2009,260.0,4.0,manual,wagon,29,21
7145,hyundai,veracruz,2012,260.0,6.0,automatic,4dr_suv,22,17
7146,mitsubishi,expo,1993,136.0,4.0,manual,2dr_hatchback,26,19
7147,ford,taurus,2015,365.0,6.0,automatic,sedan,25,17

Q2 What are the two features that have the biggest correlation in this dataset?

engine_hp and year
engine_hp and engine_cylinders
highway_mpg and engine_cylinders
highway_mpg and city_mpg

In [66]:
# correlation engine_hp and year
selected_df_train["engine_hp"].corr(selected_df_train["year"])

0.3345455568164391

In [67]:
# correlation engine_hp and engine_cylinders
selected_df_train["engine_hp"].corr(selected_df_train["engine_cylinders"])

0.7819780299482815

In [68]:
# correlation highway_mpg and engine_cylinders
selected_df_train["highway_mpg"].corr(selected_df_train["engine_cylinders"])

-0.595856440686465

In [69]:
# correlation highway_mpg and city_mpg
selected_df_train["highway_mpg"].corr(selected_df_train["city_mpg"])

0.8525891672814325

In [70]:
selected_df_train.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
dtype: object

In [71]:
categorical = list(selected_df_train.dtypes[selected_df_train.dtypes == "object"].index)
numerical = list(selected_df_train.dtypes[selected_df_train.dtypes != "object"].index)
categorical, numerical

(['make', 'model', 'transmission_type', 'vehicle_style'],
 ['year', 'engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg'])

In [72]:
# Q3 Which of these variables has the lowest mutual information score?
from sklearn.metrics import mutual_info_score

for c in categorical:
    score = mutual_info_score(selected_df_train[c], y_train)
    print(f"mutual inofrmation score between '{c}' and 'above_average': {round(score, 2)}")

mutual inofrmation score between 'make' and 'above_average': 0.24
mutual inofrmation score between 'model' and 'above_average': 0.46
mutual inofrmation score between 'transmission_type' and 'above_average': 0.02
mutual inofrmation score between 'vehicle_style' and 'above_average': 0.08

In [73]:
# one-hot encoding
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = selected_df_train[categorical + numerical].to_dict(orient="records")
X_train = dv.fit_transform(train_dict)

val_dict = selected_df_val[categorical + numerical].to_dict(orient="records")
X_val = dv.transform(val_dict)

In [74]:
# training logistic regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver="liblinear", C=10, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [75]:
model.intercept_[0]

-0.36217058412908215

In [76]:
model.coef_[0].round(3)

array([ 7.800e-02, -1.210e-01,  3.700e-02, -3.000e-03,  1.354e+00,
        1.807e+00,  5.980e-01,  2.916e+00,  1.790e-01,  2.393e+00,
        0.000e+00, -4.910e-01,  2.360e+00, -1.502e+00, -1.418e+00,
       -3.858e+00,  3.770e-01, -5.140e-01, -1.915e+00,  6.240e-01,
       -9.780e-01, -1.316e+00, -2.450e-01, -2.695e+00,  3.270e-01,
       -1.532e+00,  1.100e-02,  1.956e+00,  1.328e+00,  1.204e+00,
        4.043e+00,  1.059e+00,  5.000e-03, -1.665e+00,  0.000e+00,
        9.410e-01, -2.019e+00, -9.940e-01, -1.443e+00, -3.520e-01,
       -3.204e+00,  2.022e+00,  9.830e-01,  9.160e-01, -2.360e-01,
        3.330e-01, -2.734e+00, -1.930e+00,  3.256e+00, -7.680e-01,
       -7.360e-01,  1.191e+00, -4.150e-01, -4.800e-02, -9.000e-03,
       -1.355e+00, -2.000e-03, -9.280e-01, -3.000e-03, -4.000e-03,
       -3.000e-03, -1.211e+00, -1.900e-01,  4.350e-01, -4.650e-01,
       -6.600e-02, -1.690e-01, -1.690e-01, -0.000e+00, -1.600e-02,
       -9.900e-01,  1.570e-01,  2.600e-02,  3.600e-02,  1.706e+00,
       -6.220e-01, -7.900e-02,  1.030e-01,  0.000e+00,  1.508e+00,
        8.650e-01,  1.807e+00,  4.480e-01, -2.700e-02, -5.200e-02,
       -2.547e+00, -8.000e-02, -4.500e-02, -2.890e-01,  2.600e-02,
       -2.630e-01,  2.000e-03,  0.000e+00,  2.600e-02,  0.000e+00,
        1.252e+00,  9.400e-01, -1.080e-01, -2.531e+00, -4.000e-03,
        2.000e-03,  3.000e-03, -7.000e-03,  4.570e-01,  1.820e-01,
       -5.500e-02, -7.000e-03, -2.800e-02,  1.970e-01, -5.600e-02,
       -1.081e+00, -1.552e+00, -1.620e-01,  9.500e-01,  7.560e-01,
       -1.001e+00,  4.930e-01,  3.200e-01, -2.390e-01, -3.400e-01,
       -1.000e-01,  8.310e-01, -4.290e-01, -1.200e-02, -1.380e-01,
       -4.720e-01, -9.300e-02, -8.510e-01, -1.030e+00, -9.830e-01,
        1.544e+00,  1.370e+00,  6.840e-01,  2.860e-01,  1.768e+00,
        1.184e+00, -8.000e-03, -3.000e-03, -1.056e+00, -1.530e-01,
       -2.520e-01, -7.000e-02, -9.000e-03,  5.900e-02,  4.900e-02,
        1.000e-03, -5.300e-02, -7.000e-03, -6.300e-02, -3.630e-01,
        1.477e+00, -1.220e-01,  0.000e+00,  0.000e+00, -6.780e-01,
       -3.600e-02, -1.040e-01,  1.000e-03,  2.243e+00,  5.500e-02,
       -5.350e-01, -0.000e+00, -2.000e-02, -1.000e-02, -1.426e+00,
       -2.730e-01, -9.100e-02,  1.600e+00, -9.120e-01,  1.398e+00,
       -9.000e-02,  0.000e+00, -3.000e-03, -1.840e-01, -3.000e-03,
       -2.620e-01, -2.100e-02,  1.200e-02,  1.000e-03, -3.080e-01,
       -3.000e-03, -4.000e-03, -6.000e-03, -6.790e-01, -3.700e-02,
       -2.070e-01, -1.639e+00, -4.000e-03,  9.800e-01,  3.890e-01,
       -3.600e-02, -1.350e-01, -1.302e+00,  6.630e-01, -7.170e-01,
       -2.000e-03, -8.000e-03, -1.000e-03,  3.000e-03, -1.410e-01,
       -2.500e-02,  1.465e+00, -1.030e-01, -2.500e-02, -8.000e-03,
       -1.110e-01, -5.480e-01, -4.100e-02,  3.330e-01, -3.400e-02,
       -3.240e-01,  8.980e-01, -8.000e-03, -2.301e+00, -7.930e-01,
       -3.520e-01, -5.100e-01, -1.895e+00, -5.900e-02, -5.900e-02,
       -6.000e-03,  0.000e+00, -1.760e-01, -2.780e-01, -9.000e-03,
        1.100e-01,  8.170e-01,  4.160e-01,  1.055e+00, -1.000e-03,
       -2.900e-02, -1.600e-02, -1.492e+00, -1.787e+00, -1.700e-02,
       -2.000e-03, -2.890e-01, -1.000e-03, -3.000e-03, -5.410e-01,
        2.100e-02, -5.190e-01, -2.000e-03,  1.394e+00,  1.870e-01,
       -1.050e-01, -1.387e+00, -1.400e-02, -1.470e-01,  2.297e+00,
        1.000e-03,  0.000e+00,  5.000e-03,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00, -2.000e-03,
        1.340e-01, -1.040e-01, -2.000e-03, -2.000e-03,  7.640e-01,
        7.300e-02,  3.650e-01, -4.870e-01, -1.800e-02, -9.000e-03,
       -8.500e-02, -4.980e-01, -1.900e-02, -2.700e-02, -7.400e-02,
       -1.700e-02,  5.380e-01,  1.293e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  2.800e-02, -5.200e-02, -8.000e-03, -4.000e-03,
       -5.000e-03, -2.300e-02, -2.200e-02, -3.400e-02, -6.000e-02,
       -3.260e-01, -4.920e-01,  5.660e-01, -1.130e-01, -2.800e-02,
        0.000e+00, -3.000e-03,  8.000e-03,  1.000e-03,  2.700e-02,
       -5.400e-02,  1.424e+00,  3.000e-03, -5.000e-02,  4.260e-01,
       -2.860e-01, -6.080e-01,  1.310e+00,  3.332e+00, -1.000e-03,
       -1.000e-02, -1.100e-02,  3.469e+00, -1.273e+00, -5.700e-02,
       -1.300e-01, -8.010e-01, -9.000e-03, -3.600e-02, -4.380e-01,
       -9.430e-01, -1.170e-01, -5.500e-02, -5.300e-02, -6.000e-03,
       -6.000e-03, -3.000e-03, -2.990e-01, -1.100e-02, -6.500e-02,
        1.317e+00,  1.774e+00, -1.470e-01, -1.930e-01, -6.400e-02,
        9.540e-01, -1.646e+00, -1.366e+00, -3.100e-01,  5.450e-01,
       -2.530e-01, -2.560e-01,  2.810e-01, -6.000e-03, -2.010e-01,
        7.220e-01,  4.600e-02,  2.600e-02,  3.900e-02,  2.040e-01,
       -7.900e-02, -1.340e-01, -2.000e-03,  1.900e-01, -2.000e-02,
       -2.600e-02,  1.123e+00, -2.284e+00, -2.745e+00, -0.000e+00,
        1.414e+00,  2.187e+00,  3.620e-01, -4.600e-02, -5.710e-01,
       -2.000e-03, -5.410e-01, -7.900e-02,  1.509e+00, -1.500e-02,
       -8.300e-02, -2.000e-02,  0.000e+00,  6.200e-02, -0.000e+00,
        0.000e+00, -7.000e-03, -5.600e-01, -1.100e-02, -6.500e-02,
       -5.980e-01, -8.920e-01,  1.000e-01,  2.000e-03, -3.800e-02,
       -3.300e-02, -1.700e-02, -3.660e-01, -6.200e-02, -1.000e-03,
       -1.390e-01, -3.870e-01, -2.400e-02, -6.800e-02, -1.055e+00,
       -1.830e-01, -1.460e-01,  1.056e+00,  1.670e-01,  2.480e-01,
        2.800e-02,  2.700e-02, -2.400e-02, -0.000e+00, -1.962e+00,
       -1.641e+00,  3.030e-01, -7.730e-01, -7.380e-01, -5.000e-03,
       -1.540e-01, -9.030e-01,  6.240e-01,  6.000e-01,  3.050e-01,
       -1.038e+00, -1.300e-02,  7.000e-03,  5.320e-01, -1.126e+00,
        2.110e-01,  1.000e-03,  1.000e-03,  9.060e-01, -6.970e-01,
       -4.540e-01,  1.003e+00,  2.400e-02, -2.110e-01, -2.443e+00,
        2.000e-03, -6.800e-02, -1.100e-02, -2.990e-01, -3.510e-01,
       -1.530e-01, -1.800e-02, -2.670e-01, -3.460e-01, -5.900e-02,
       -2.900e-02,  1.220e-01,  5.100e-02,  1.300e-02,  1.633e+00,
        7.810e-01,  8.240e-01, -1.036e+00,  2.890e-01,  7.900e-02,
        2.630e-01,  1.400e-02,  7.000e-03, -2.340e-01, -6.390e-01,
        3.410e-01,  1.057e+00,  4.770e-01, -7.220e-01, -1.180e-01,
        5.360e-01,  8.140e-01, -0.000e+00, -5.200e-02, -5.320e-01,
        0.000e+00, -2.270e-01,  5.000e-03, -2.890e-01, -2.940e-01,
       -6.000e-03, -7.850e-01, -1.800e-02,  2.300e-01, -6.300e-01,
       -1.000e-03, -4.500e-02, -2.340e-01, -7.000e-03, -1.120e-01,
       -2.800e-02, -1.110e-01, -3.000e-03, -6.220e-01, -4.600e-01,
        5.060e-01, -2.380e-01, -6.310e-01,  5.500e-02,  1.000e-02,
       -1.410e-01, -4.690e-01, -5.160e-01, -1.740e-01, -1.450e-01,
       -2.240e-01, -5.350e-01, -9.900e-02, -0.000e+00,  4.940e-01,
        7.430e-01, -1.240e-01, -1.189e+00, -2.900e-02, -3.060e-01,
       -9.000e-03,  9.700e-02, -1.500e-02, -6.000e-03, -1.000e-03,
       -7.400e-02, -1.490e-01, -4.960e-01, -6.500e-02,  7.000e-03,
        0.000e+00, -8.600e-02, -1.000e-03, -1.700e-01,  2.900e-01,
        1.950e-01, -4.010e-01, -9.450e-01,  3.520e-01,  3.540e-01,
        5.000e-03, -3.000e-02, -6.000e-03,  7.950e-01, -1.600e-02,
       -3.000e-03, -1.300e-01,  6.460e-01,  5.900e-02,  1.086e+00,
        1.653e+00,  1.000e-01,  1.100e-02, -8.300e-02,  1.783e+00,
        2.400e-01,  2.400e-02,  1.084e+00,  0.000e+00,  3.800e-02,
        0.000e+00,  0.000e+00,  3.990e-01, -1.246e+00, -3.090e-01,
       -3.400e-02, -1.000e-02, -4.400e-02, -3.700e-02, -1.135e+00,
       -4.230e-01, -9.410e-01, -7.000e-03, -1.109e+00,  0.000e+00,
       -1.200e-02, -2.400e-02, -4.000e-03,  1.718e+00, -1.990e-01,
       -0.000e+00, -0.000e+00, -7.300e-02, -5.000e-03, -1.000e-03,
       -1.860e-01, -7.580e-01,  5.010e-01, -9.930e-01,  5.760e-01,
       -2.010e-01,  3.256e+00, -1.000e-03, -4.300e-02, -6.000e-03,
       -1.730e-01, -4.000e-02, -1.640e-01,  0.000e+00, -7.000e-02,
       -6.000e-03, -3.600e-02,  3.000e-03,  1.178e+00,  1.485e+00,
        0.000e+00, -1.812e+00, -7.310e-01, -1.000e-03, -2.040e-01,
       -2.000e-03, -7.000e-03,  1.730e-01, -2.500e-02, -1.290e-01,
       -2.600e-02, -4.900e-02, -1.690e-01,  1.952e+00, -4.000e-03,
       -1.000e-03, -2.088e+00,  2.400e-01,  1.947e+00, -0.000e+00,
       -5.140e-01, -7.500e-02, -3.270e-01, -1.770e-01, -1.710e-01,
       -3.280e-01,  5.380e-01,  7.450e-01, -2.000e-03, -5.220e-01,
       -1.630e-01,  1.750e-01,  1.579e+00,  4.000e-02,  2.800e-02,
        6.000e-03, -2.000e-03, -9.000e-03, -0.000e+00, -1.600e-02,
       -3.300e-02, -6.500e-02, -1.900e-02, -6.000e-03, -9.100e-02,
       -3.000e-03, -1.000e-03, -2.000e-03, -1.000e-03,  4.950e-01,
       -1.600e-02, -1.657e+00, -6.490e-01,  2.200e-01,  6.510e-01,
        7.400e-01,  4.700e-01,  2.691e+00,  6.690e-01,  1.325e+00,
        1.590e-01,  5.950e-01,  6.200e-02, -4.080e-01, -2.380e+00,
        4.860e-01,  2.095e+00,  5.250e-01,  8.500e-02,  2.276e+00,
       -1.700e-02,  1.800e-02, -1.500e-02, -9.000e-02, -1.141e+00,
       -1.200e-02, -5.000e-03, -3.000e-03, -0.000e+00, -5.000e-03,
       -1.311e+00, -5.000e-03, -0.000e+00, -1.900e-02,  2.640e-01,
        2.089e+00,  1.970e-01, -1.400e-02,  1.800e-02,  1.000e-03,
       -3.870e-01,  1.162e+00, -2.570e-01, -4.990e-01,  1.104e+00,
        6.530e-01, -2.350e+00, -2.900e-02, -7.840e-01, -1.700e-02,
       -4.500e-02, -4.000e-03,  0.000e+00,  1.650e-01, -3.000e-02,
       -6.000e-02,  1.308e+00,  8.400e-01, -4.580e-01, -2.290e-01,
       -4.000e-02, -2.600e-02, -2.870e-01,  2.100e-02,  4.000e-03,
        0.000e+00, -3.700e-02, -3.900e-02, -6.000e-02, -7.680e-01,
       -9.380e-01,  8.140e-01,  4.050e-01,  1.950e-01, -1.100e-02,
       -1.900e-02, -1.000e-03, -1.200e-02,  1.500e-02, -2.790e-01,
        1.600e-01,  2.890e-01, -4.150e-01,  1.990e-01,  5.000e-03,
       -4.570e-01,  5.880e-01,  4.000e-03, -2.760e-01,  0.000e+00,
        6.150e-01,  1.220e-01, -1.300e-02, -1.800e-02, -0.000e+00,
       -7.920e-01, -3.120e-01, -7.520e-01, -2.980e-01, -2.930e-01,
       -8.060e-01,  1.320e-01, -1.000e-03, -3.650e-01, -6.400e-02,
       -5.100e-02, -4.000e-03,  1.104e+00,  6.720e-01, -2.000e-03,
        3.900e-02,  0.000e+00, -7.000e-03,  8.240e-01,  1.513e+00,
       -9.360e-01,  1.045e+00, -6.610e-01, -8.100e-02, -7.000e-03,
       -1.000e-03, -8.600e-02,  7.750e-01,  1.598e+00, -6.840e-01,
        1.866e+00, -2.000e-02,  4.200e-02,  9.000e-03,  9.500e-01,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00, -7.400e-02,
       -1.690e-01, -2.720e-01, -8.300e-02, -3.000e-02, -4.000e-03,
       -5.580e-01, -1.800e-02, -4.300e-02, -3.000e-03, -1.804e+00,
       -1.900e-02, -0.000e+00, -3.540e-01, -1.000e-02,  7.000e-02,
        3.700e-02,  3.000e-03, -1.172e+00, -4.000e-03, -5.800e-02,
       -1.300e-02,  4.560e-01,  2.000e-03,  1.305e+00, -3.000e-03,
       -3.000e-03, -1.000e-03, -6.000e-03, -2.900e-02, -1.000e-03,
       -2.800e-02, -1.800e-02, -6.000e-03, -8.400e-01,  1.914e+00,
        1.161e+00, -8.700e-02, -8.470e-01, -3.270e-01, -4.800e-02,
       -1.000e-03, -1.000e-03, -4.060e-01, -2.770e-01, -1.050e+00,
       -7.000e-03, -4.880e-01, -1.369e+00,  3.200e-02, -4.760e-01,
       -1.000e-02, -1.770e-01,  3.335e+00,  2.100e-02, -7.100e-02,
        2.588e+00, -2.200e-02, -3.396e+00, -9.080e-01, -1.600e-02,
       -9.100e-02,  1.655e+00,  3.600e-01, -6.300e-02, -2.080e-01,
       -4.300e-01, -6.100e-02, -5.000e-03, -1.085e+00, -4.270e-01,
        3.800e-01,  1.580e-01, -9.000e-02, -1.032e+00, -2.300e-01,
       -3.170e-01,  3.100e-02,  1.300e-02,  1.000e-03, -1.190e-01,
       -5.950e-01, -5.450e-01,  1.698e+00, -1.900e-01,  4.960e-01,
       -1.000e-03, -1.000e-03, -6.000e-03,  1.000e-03, -0.000e+00,
       -3.900e-02, -4.700e-02, -1.027e+00, -3.670e-01, -3.420e-01,
       -1.000e-02, -1.500e-02, -5.000e-03,  0.000e+00, -3.000e-03,
       -2.600e-02,  1.500e-02,  1.000e-03, -1.500e-02, -4.500e-02,
       -7.800e-02, -1.200e-02,  0.000e+00, -5.700e-01, -1.000e-03,
       -2.097e+00, -1.520e-01,  6.320e-01,  4.210e-01,  0.000e+00,
        1.820e-01,  0.000e+00, -4.000e-03, -3.100e-02, -5.800e-02,
        2.700e-01,  7.200e-01,  1.427e+00, -6.000e-03, -4.000e-03,
       -1.300e-02, -1.390e-01, -1.200e+00,  1.470e-01,  2.000e-03,
       -1.000e-03,  8.000e-02, -7.570e-01,  9.890e-01, -4.300e-02,
       -8.000e-03, -1.000e-03,  8.470e-01, -7.200e-02,  9.990e-01,
        1.075e+00, -9.360e-01,  3.140e-01,  3.810e-01,  1.800e-02,
        1.928e+00,  3.200e-02, -4.800e-02,  5.280e-01, -7.830e-01,
       -9.200e-02, -1.739e+00,  3.170e-01, -1.186e+00,  1.201e+00,
       -1.810e-01, -4.810e-01,  1.979e+00,  1.480e+00, -2.040e-01,
        3.770e-01, -1.024e+00,  1.103e+00,  2.040e-01, -3.062e+00,
        4.700e-01,  3.830e-01, -6.000e-03])

In [77]:
# Q4 What accuracy did you get?
y_pred = model.predict_proba(X_val)[:, 1]
price_decision = (y_pred >= 0.5)
round((price_decision == y_val).mean(),2)

0.95

Q5 Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
For each feature, calculate the difference between the original accuracy and the accuracy without the feature.
Which of following feature has the smallest difference?

- year
- engine_hp
- transmission_type
- city_mpg

In [78]:
dv_no_year = DictVectorizer(sparse=False)

selected_df_train_no_year = selected_df_train[
    ["make",
    "model",
    "engine_hp",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]
]

selected_df_train_no_year
selected_df_val_no_year = selected_df_val[
    ["make",
    "model",
    "engine_hp",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]
]

train_dict_no_year = selected_df_train_no_year[["make",
    "model",
    "engine_hp",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]].to_dict(orient="records")
X_train_no_year = dv_no_year.fit_transform(train_dict_no_year)

val_dict_no_year = selected_df_val_no_year[["make",
    "model",
    "engine_hp",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]].to_dict(orient="records")
X_val_no_year = dv_no_year.transform(val_dict_no_year)

In [79]:
# training logistic regression no year

model_no_year = LogisticRegression(solver="liblinear", C=10, max_iter=1000, random_state=42)
model_no_year.fit(X_train_no_year, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [80]:
# accuracy no year
y_pred_no_year = model_no_year.predict_proba(X_val_no_year)[:, 1]
price_decision_no_year = (y_pred_no_year >= 0.5)
round((price_decision_no_year == y_val).mean(),2)

0.95

In [81]:
# training logistic regression no_engine_hp
dv_no_engine_hp = DictVectorizer(sparse=False)

selected_df_train_no_engine_hp = selected_df_train[
    ["make",
     "year",
    "model",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]
]

selected_df_val_no_engine_hp = selected_df_val[
    ["make",
     "year",
    "model",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]
]

train_dict_no_engine_hp = selected_df_train_no_engine_hp[["make",
     "year",
    "model",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]].to_dict(orient="records")
X_train_no_engine_hp = dv_no_engine_hp.fit_transform(train_dict_no_engine_hp)

val_dict_no_engine_hp = selected_df_val_no_engine_hp[["make",
     "year",
    "model",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]].to_dict(orient="records")
X_val_no_engine_hp = dv_no_engine_hp.transform(val_dict_no_engine_hp)


model_no_engine_hp = LogisticRegression(solver="liblinear", C=10, max_iter=1000, random_state=42)
model_no_engine_hp.fit(X_train_no_engine_hp, y_train)

# accuracy _no_engine_hp
y_pred_no_engine_hp = model_no_engine_hp.predict_proba(X_val_no_engine_hp)[:, 1]
price_decision_no_engine_hp = (y_pred_no_engine_hp >= 0.5)
round((price_decision_no_engine_hp == y_val).mean(),2)

0.92

In [82]:
# training logistic regression no transmission_type
dv_no_transmission_type = DictVectorizer(sparse=False)

selected_df_train_no_transmission_type = selected_df_train[
    ["make",
     "year",
    "model",
    "engine_cylinders",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]
]

selected_df_val_no_transmission_type = selected_df_val[
    ["make",
     "year",
    "model",
    "engine_cylinders",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]
]

train_dict_no_transmission_type = selected_df_train_no_transmission_type[["make",
     "year",
    "model",
    "engine_cylinders",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]].to_dict(orient="records")
X_train_no_transmission_type = dv_no_transmission_type.fit_transform(train_dict_no_transmission_type)

val_dict_no_transmission_type = selected_df_val_no_transmission_type[["make",
     "year",
    "model",
    "engine_cylinders",
    "vehicle_style",
    "highway_mpg",
    "city_mpg"
    ]].to_dict(orient="records")
X_val_no_transmission_type = dv_no_transmission_type.transform(val_dict_no_transmission_type)


model_no_transmission_type = LogisticRegression(solver="liblinear", C=10, max_iter=1000, random_state=42)
model_no_transmission_type.fit(X_train_no_transmission_type, y_train)

# accuracy _no_engine_hp
y_pred_no_transmission_type = model_no_transmission_type.predict_proba(X_val_no_transmission_type)[:, 1]
price_decision_no_transmission_type = (y_pred_no_transmission_type >= 0.5)
round((price_decision_no_transmission_type == y_val).mean(),2)

0.92

In [83]:
# training logistic regression no city_mpg
dv_no_city_mpg = DictVectorizer(sparse=False)

selected_df_train_no_city_mpg = selected_df_train[
    ["make",
     "year",
    "model",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg"
    ]
]

selected_df_val_no_city_mpg = selected_df_val[
    ["make",
     "year",
    "model",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg"
    ]
]

train_dict_no_city_mpg = selected_df_train_no_city_mpg[["make",
     "year",
    "model",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg"
    ]].to_dict(orient="records")
X_train_no_city_mpg = dv_no_city_mpg.fit_transform(train_dict_no_city_mpg)

val_dict_no_city_mpg = selected_df_val_no_city_mpg[["make",
     "year",
    "model",
    "engine_cylinders",
    "transmission_type",
    "vehicle_style",
    "highway_mpg"
    ]].to_dict(orient="records")
X_val_no_city_mpg = dv_no_city_mpg.transform(val_dict_no_city_mpg)


model_no_city_mpg = LogisticRegression(solver="liblinear", C=10, max_iter=1000, random_state=42)
model_no_city_mpg.fit(X_train_no_city_mpg, y_train)

# accuracy no_city_mpg
y_pred_no_city_mpg = model_no_city_mpg.predict_proba(X_val_no_city_mpg)[:, 1]
price_decision_no_city_mpg = (y_pred_no_city_mpg >= 0.5)
round((price_decision_no_city_mpg == y_val).mean(),2)

0.92

Q6 For this question, we'll see how to use a linear regression model from Scikit-Learn.
We'll need to use the original column price. Apply the logarithmic transformation to this column.
Fit the Ridge regression model on the training data with a solver 'sag'. Set the seed to 42.
This model also has a parameter alpha. Let's try the following values: [0, 0.01, 0.1, 1, 10].
Round your RMSE scores to 3 decimal digits.
Which of these alphas leads to the best RMSE on the validation set?

0
0.01
0.1
1
10

In [84]:
# format the data
df_copy = df[
    ["Make",
    "Model",
    "Year",
    "Engine HP",
    "Engine Cylinders",
    "Transmission Type",
    "Vehicle Style",
    "highway MPG",
    "city mpg",
    "MSRP"]
].copy()

df_copy.columns = df_copy.columns.str.replace(" ", "_").str.lower()
df_copy_columns = list(df_copy.dtypes.index)

for c in df_copy_columns:
    if df_copy[c].dtype == "object":
        df_copy[c] = df_copy[c].str.lower().str.replace(" ", "_")
        
df_copy = df_copy.rename(columns={"msrp": "price"})
df_copy.fillna(0, inplace=True)
df_copy.isnull().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
price                0
dtype: int64

In [93]:
df_copy["price"] = np.log1p(df_copy["price"])

In [94]:
# split the data
df_copy_full_train, df_copy_test = train_test_split(df_copy, test_size=0.2, random_state=42)
df_copy_train, df_copy_val = train_test_split(df_copy_full_train, test_size=0.25, random_state=42)

df_copy_train = df_copy_train.reset_index(drop=True)
df_copy_val = df_copy_val.reset_index(drop=True)
df_copy_test = df_copy_test.reset_index(drop=True)

df_copy_y_train = df_copy_train["price"].values
df_copy_y_val = df_copy_val["price"].values
df_copy_y_test = df_copy_test["price"].values

del df_copy_train["price"]
del df_copy_val["price"]
del df_copy_test["price"]

len(df_copy_train)

7148

In [95]:
df_copy_y_train.shape, df_copy_y_val.shape

((7148,), (2383,))

In [96]:
df_copy_train.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
dtype: object

In [97]:
# one-hot encoding
dv_copy = DictVectorizer(sparse=False)
# new_columns = list(df_copy_train.dtypes.index)
train_dict_copy = df_copy_train.to_dict(orient="records")
X_train_copy = dv_copy.fit_transform(train_dict_copy)

val_dict_copy = df_copy_val.to_dict(orient="records")
X_val_copy = dv_copy.transform(val_dict_copy)

In [98]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import warnings
warnings.filterwarnings("ignore")

scores = {}
alphas = [0, 0.01, 0.1, 1, 10]

for alpha in alphas:
    model = Ridge(alpha=alpha, solver="sag", max_iter=1000, random_state=42)
    model.fit(X_train_copy, df_copy_y_train)
    # predict on validation set
    y_pred_df_copy = model.predict(X_val_copy)
    # calculate rmse
    score = mean_squared_error(df_copy_y_val, y_pred_df_copy, squared=False)
    scores[alpha] = round(score, 3)
    print(f"alpha = {alpha}:\t RMSE = {score}")

alpha = 0:	 RMSE = 0.48679431324238887
alpha = 0.01:	 RMSE = 0.48679455192752613
alpha = 0.1:	 RMSE = 0.48679670001899733
alpha = 1:	 RMSE = 0.4868181745432738
alpha = 10:	 RMSE = 0.4870322832975125

In [99]:
scores

{0: 0.487, 0.01: 0.487, 0.1: 0.487, 1: 0.487, 10: 0.487}